version: '3'

services:
  back:
    image: melissapanduro/backPRS2
    ports:
      - "8085:8085"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  front:
    image: melissapanduro/frontPRS2
    ports:
      - "4200:4200"
    environment:
      API_BACKEND: ${API_BACKEND}
    depends_on:
      - back